import type { KnipConfig } from 'knip'

const config: KnipConfig = {
  treatConfigHintsAsErrors: true,
  workspaces: {
    '.': {
      entry: [
        '{build,scripts}/**/*.{js,ts}',
        'src/assets/css/style.css',
        'src/scripts/ui/menu/index.ts',
        'src/types/index.ts',
        // Public extension API surface — published package entry point.
        // Per AGENTS.md, this barrel is the explicit exception to the
        // no-barrel-files-in-src rule because it IS the package entry.
        'src/extension-api/index.ts',
        'src/storybook/mocks/**/*.ts'
      ],
      project: ['**/*.{js,ts,vue}', '*.{js,ts,mts}', '!.claude/**']
    },
    'apps/desktop-ui': {
      entry: ['src/i18n.ts'],
      project: ['src/**/*.{js,ts,vue}']
    },
    'packages/design-system': {
      project: ['src/**/*.{css,js,ts}']
    },
    'packages/tailwind-utils': {
      project: ['src/**/*.{js,ts}']
    },
    'packages/shared-frontend-utils': {
      project: ['src/**/*.{js,ts}']
    },
    'packages/registry-types': {
      project: ['src/**/*.{js,ts}']
    },
    'packages/ingest-types': {
      project: ['src/**/*.{js,ts}']
    },
    'apps/website': {
      entry: ['src/scripts/**/*.ts']
    }
  },
  ignoreBinaries: ['python3'],
  ignoreDependencies: [
    // Weird importmap things
    '@iconify-json/lucide',
    '@iconify/json',
    '@primeuix/forms',
    '@primeuix/styled',
    '@primeuix/utils',
    '@primevue/icons'
  ],
  ignore: [
    // Auto generated API types
    'src/workbench/extensions/manager/types/generatedManagerTypes.ts',
    'packages/ingest-types/src/zod.gen.ts',
    // Workflow files contain license names that knip misinterprets as binaries
    '.github/workflows/ci-oss-assets-validation.yaml',
    // Pending integration in stacked PR
    'src/components/sidebar/tabs/nodeLibrary/CustomNodesPanel.vue',
    // Marketing media tooling — adopted by pages in a follow-up PR
    'apps/website/src/components/common/SiteVideo.vue',
    'apps/website/src/utils/marketingImage.ts',
    // Agent review check config, not part of the build
    '.agents/checks/eslint.strict.config.js',
    // Devtools extensions, included dynamically
    'tools/devtools/web/**',
    // Deprecated stub re-exporting from `@/extension-api`. Will be removed
    // once PKG2 (`@comfyorg/extension-api`) ships and downstream imports
    // migrate to the package path.
    'src/types/extensionV2.ts',
    // Reviewable snapshot of @comfyorg/extension-api .d.ts surface.
    // Generated by `pnpm --filter @comfyorg/extension-api build` and
    // copied here so reviewers can diff public-API changes without
    // having to build the package locally. Not consumed at runtime.
    'packages/extension-api/api-snapshot/**',
    // Strangler-pattern v2 conversions of core extensions. Not yet wired
    // into the bootstrap (registration lands in a follow-up PR alongside
    // the v1→v2 cut-over). Tracked by I-EXT (#12144).
    'src/extensions/core/noteNode.v2.ts',
    'src/extensions/core/rerouteNode.v2.ts',
    'src/extensions/core/slotDefaults.v2.ts',
    // Test framework harness for v2 extension migration. Consumed by
    // colocated *.v2.test.ts / *.migration.test.ts files; knip's vitest
    // entry resolution does not yet see these as test infra. Tracked by
    // I-TF (#12145).
    'src/extension-api-v2/harness/**'
  ],
  vite: {
    config: ['vite?(.*).config.mts']
  },
  vitest: {
    config: ['vitest?(.*).config.ts'],
    entry: [
      '**/*.{bench,test,test-d,spec}.?(c|m)[jt]s?(x)',
      '**/__mocks__/**/*.[jt]s?(x)'
    ]
  },
  playwright: {
    config: ['playwright?(.*).config.ts'],
    entry: ['**/*.@(spec|test).?(c|m)[jt]s?(x)', 'browser_tests/**/*.ts']
  },
  tags: [
    '-knipIgnoreUnusedButUsedByCustomNodes',
    '-knipIgnoreUnusedButUsedByVueNodesBranch',
    '-knipIgnoreUsedByStackedPR',
    // Public API surface consumed externally by extension authors and the
    // TypeDoc docgen pipeline (PKG2). Mark exports with @publicAPI when they
    // are part of `@comfyorg/extension-api` but not internally referenced.
    '-publicAPI'
  ]
}

export default config
